spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/linklearn?createDatabaseIfNotExist=true
    username: root
    password: n12301230!
    driver-class-name: com.mysql.cj.jdbc.Driver
